version: 2.1

orbs:
  slack: circleci/slack@4.2.0

executors:
  node-executor:
    docker:
      - image: cimg/node:20.8.0
    working_directory: ~/repo
  slack-executor:
    docker:
      - image: 'cibuilds/base:latest'
    resource_class: small

aliases:
  - &show-current-branch
    run:
      name: Show Current Branch
      command: echo ${CIRCLE_BRANCH}
  - &restore-cache
    restore_cache:
      keys:
        - app-{{checksum "package.json"}}
        - app-
  - &install-packages
    run: 
      name: Install Dependencies
      command: npm install
  - &save-cache
    save_cache:
          paths:
            - node_modules
          key: app-{{checksum "package.json"}}

jobs: 
  build: 
    executor: node-executor
    steps:
      - checkout
      - *show-current-branch
      - *restore-cache
      - *install-packages
      - *save-cache

  deploy-to-aws:
    executor: node-executor
    steps:
      - checkout
      - *show-current-branch
      - run:
          name: Install AWS CLI
          working_directory: /
          command: |
            sudo apt-get -y update
            sudo apt-get install -y unzip curl
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
            unzip /tmp/awscliv2.zip -d /tmp
            sudo /tmp/aws/install
      - run:
          name: Build Project
          command: | 
            npm install
            npm run build
            cd build
            zip ../build.zip -r *.[^.]* 
            echo "Build Successful"
      - run:
          name: Deploy to AWS S3
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_BUCKET_PROD} --delete
              echo "Deployed to S3"
            elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_BUCKET_STAGING} --delete
              echo "Deployed to S3"
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_BUCKET_DEV} --delete
              echo "Deployed to S3"
            else
              echo "Branch not found"
            fi
         

  deploy-to-cloudfront:
    executor: node-executor
    steps:
      - checkout
      - *show-current-branch
      - run:
          name: Install AWS CLI
          working_directory: /
          command: |
            sudo apt-get -y update
            sudo apt-get install -y unzip curl
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
            unzip /tmp/awscliv2.zip -d /tmp
            sudo /tmp/aws/install
      - run:
          name: Build Project
          command: | 
            npm install
            npm run build
            cd build
            zip ../build.zip -r *.[^.]* 
            echo "Build Successful" 
      - run:
          name: Deploy to AWS CloudFront
          command: |
            aws configure set preview.cloudfront true
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws cloudfront create-invalidation --distribution-id ${PROD_CDN_ID} --paths "/*"
              echo "Deployed to CloudFront"
            elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
              aws cloudfront create-invalidation --distribution-id ${STAGING_CDN_ID} --paths "/*"
              echo "Deployed to CloudFront"
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
              aws cloudfront create-invalidation --distribution-id ${DEV_CDN_ID} --paths "/*"
              echo "Deployed to CloudFront"
            else
              echo "Branch not found"
            fi

  notify-via-slack:
    executor: slack-executor
    steps:
      - run: echo "Slack notification"
      - slack/notify:
          event: 'always'
          channel: 'cicdfe'
          template: ''
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*Build Status:* {{build_status}}",
                      "emoji": true
                    },
                    {
                      "type": "plain_text",
                      "text": "*Project:* {{project}}",
                      "emoji": true
                    },
                    {
                      "type": "plain_text",
                      "text": "*Build URL:* <{{build_url}}|Click here to view the build>",
                      "emoji": true
                    }
                  ]
                }
              ]
            }

          


workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy-to-aws:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - staging
                - develop
      - deploy-to-cloudfront:
          requires:
            - deploy-to-aws
          filters:
            branches:
              only:
                - master
                - staging
                - develop
      - notify-via-slack:
          requires:
            - deploy-to-cloudfront
          filters:
            branches:
              only:
                - master
                - staging
                - develop
