version: 2.1

jobs: 
  build: 
    docker:
      - image: cimg/node:20.8.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: Show Current Branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - app-{{checksum "package.json"}}
            - app-
      - run: 
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: app-{{checksum "package.json"}}

  deploy-to-aws:
    docker:
      - image: cimg/node:20.8.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show Current Branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Install AWS CLI
          working_directory: /
          command: |
            sudo apt-get -y update
            sudo apt-get install -y unzip curl
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
            unzip /tmp/awscliv2.zip -d /tmp
            sudo /tmp/aws/install
      - run:
          name: Build Project
          command: | 
            npm install
            npm run build
            cd build
            zip ../build.zip -r *.[^.]* 
            echo "Build Successful"
      - run:
          name: Deploy to AWS S3
          command: |
            if [ ${CIRCLE_BRANCH} == "master" ]; then
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_BUCKET_PROD} --delete
              echo "Deployed to S3"
            elif [ ${CIRCLE_BRANCH} == "staging" ]; then
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_BUCKET_STAGING} --delete
              echo "Deployed to S3"
            elif [ ${CIRCLE_BRANCH} == "development" ]; then
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_BUCKET_DEV} --delete
              echo "Deployed to S3"
            else
              echo "Branch not found"
            fi           

  deploy-to-cloudfront:
    docker:
      - image: cimg/node:20.8.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show Current Branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Install AWS CLI
          working_directory: /
          command: |
            sudo apt-get -y update
            sudo apt-get install -y unzip curl
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
            unzip /tmp/awscliv2.zip -d /tmp
            sudo /tmp/aws/install
      - run:
          name: Build Project
          command: | 
            npm install
            npm run build
            cd build
            zip ../build.zip -r *.[^.]* 
            echo "Build Successful" 
      - run:
          name: Deploy to AWS CloudFront
          command: |
            aws configure set preview.cloudfront true
            if [ ${CIRCLE_BRANCH} == "master" ]; then
              aws cloudfront create-invalidation --distribution-id ${PROD_CDN_ID} --paths "/*"
              echo "Deployed to CloudFront"
            elif [ ${CIRCLE_BRANCH} == "staging" ]; then
              aws cloudfront create-invalidation --distribution-id ${STAGING_CDN_ID} --paths "/*"
              echo "Deployed to CloudFront"
            elif [ ${CIRCLE_BRANCH} == "development" ]; then
              aws cloudfront create-invalidation --distribution-id ${DEV_CDN_ID} --paths "/*"
              echo "Deployed to CloudFront"
            else
              echo "Branch not found"
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy-to-aws:
          requires:
            - build
      - deploy-to-cloudfront:
          requires:
            - deploy-to-aws
